[package]
name = "secret-number"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
rand = { version = "0.8", features = ["std", "getrandom"] }
getrandom = { version = "0.2", features = ["js"] }

[lib]
crate-type = ["cdylib"]
